/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DatePicker: typeof import('./src/components/ElementForm/DatePicker.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    MyPokemon: typeof import('./src/components/Erik/MyPokemon.vue')['default']
    Origin: typeof import('./src/components/Origin/index.vue')['default']
    Parent: typeof import('./src/components/ElementForm/Parent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionBlock: typeof import('./src/components/Ithome/SectionBlock.vue')['default']
    SectionBlockTitle: typeof import('./src/components/Ithome/SectionBlockTitle.vue')['default']
    Select: typeof import('./src/components/ElementForm/Select.vue')['default']
    View: typeof import('./src/components/Erik/View.vue')['default']
  }
}
